# Form implementation generated from reading ui file 'WireFrameEditarAsignatura.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditarAsignatura(object):
    def setupUi(self, EditarAsignatura):
        EditarAsignatura.setObjectName("EditarAsignatura")
        EditarAsignatura.resize(337, 229)
        self.NombreAsignatura = QtWidgets.QLabel(EditarAsignatura)
        self.NombreAsignatura.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.NombreAsignatura.setObjectName("NombreAsignatura")
        self.txtCodigo = QtWidgets.QLineEdit(EditarAsignatura)
        self.txtCodigo.setGeometry(QtCore.QRect(140, 20, 113, 20))
        self.txtCodigo.setObjectName("txtCodigo")
        self.Nombre = QtWidgets.QLabel(EditarAsignatura)
        self.Nombre.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.Nombre.setObjectName("Nombre")
        self.txtNombre = QtWidgets.QLineEdit(EditarAsignatura)
        self.txtNombre.setGeometry(QtCore.QRect(140, 60, 113, 20))
        self.txtNombre.setObjectName("txtNombre")
        self.btnGuardar = QtWidgets.QPushButton(EditarAsignatura)
        self.btnGuardar.setGeometry(QtCore.QRect(60, 160, 75, 23))
        self.btnGuardar.setObjectName("btnGuardar")
        self.btnCancelar = QtWidgets.QPushButton(EditarAsignatura)
        self.btnCancelar.setGeometry(QtCore.QRect(150, 160, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")
        self.Creditos = QtWidgets.QLabel(EditarAsignatura)
        self.Creditos.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.Creditos.setObjectName("Creditos")
        self.Semestre = QtWidgets.QLabel(EditarAsignatura)
        self.Semestre.setGeometry(QtCore.QRect(20, 120, 111, 16))
        self.Semestre.setObjectName("Semestre")
        self.txtCreditos = QtWidgets.QLineEdit(EditarAsignatura)
        self.txtCreditos.setGeometry(QtCore.QRect(140, 90, 113, 20))
        self.txtCreditos.setObjectName("txtCreditos")
        self.txtSemestre = QtWidgets.QLineEdit(EditarAsignatura)
        self.txtSemestre.setGeometry(QtCore.QRect(140, 120, 113, 20))
        self.txtSemestre.setObjectName("txtSemestre")

        self.retranslateUi(EditarAsignatura)
        QtCore.QMetaObject.connectSlotsByName(EditarAsignatura)

    def retranslateUi(self, EditarAsignatura):
        _translate = QtCore.QCoreApplication.translate
        EditarAsignatura.setWindowTitle(_translate("EditarAsignatura", "Editar Asignatura"))
        self.NombreAsignatura.setText(_translate("EditarAsignatura", "CODIGO           :"))
        self.Nombre.setText(_translate("EditarAsignatura", "Ingrese  Nombre        :"))
        self.btnGuardar.setText(_translate("EditarAsignatura", "Guardar"))
        self.btnCancelar.setText(_translate("EditarAsignatura", "Cancelar"))
        self.Creditos.setText(_translate("EditarAsignatura", "Creditos       :"))
        self.Semestre.setText(_translate("EditarAsignatura", "Semestre       :"))
